# Generated by Django 3.1.3 on 2020-11-18 00:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('unavailable', 'Indisponível'), ('deleted', 'Deletado')], default='unavailable', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
