# Generated by Django 3.1.3 on 2020-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Perfumaria', 'Perfumaria'), ('Vestuário', 'Vestuário'), ('Eletrodomésticos', 'Eletrodomésticos'), ('Mercado', 'Mercado'), ('Decoração', 'Decoração'), ('Petshop', 'Petshop'), ('Móveis', 'Móveis'), ('Papelaria', 'Papelaria')], default='Sem categorias', max_length=20),
        ),
    ]
