# Generated by Django 3.1.3 on 2020-11-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sellers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
